/**
 * Sidebars group docs into collections for navigation
 *  Create a new sidebar object (e.g., basics: []) for each new collection
 *  
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  concepts: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'core-concepts', 
        },
      ],
    }
  ],

  tabular: [
    {
      type: 'category',
      label: 'Tabular',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tabular-models', 
        },
      ],
    }
  ],

  text: [
    {
      type: 'category',
      label: 'Text',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'text-models', 
        },
      ],
    }
  ],

  vision: [
    {
      type: 'category',
      label: 'Vision',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'vision-models', 
        },
      ],
    }
  ],

  /*
  "sidebar-all": {
    "Tutorials All": [
      'intro',
      'tutorial-extras/manage-docs-versions',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
  },
  */
  
};

export default sidebars;
